SALESPERSON_INDEX = 0
INTERNET_INDEX = 1
DORKY_LINE_LENGTH = 80

# Print out starting divider
print("*" * DORKY_LINE_LENGTH)

# Open order by type file
f = open("orders-by-type.txt")

melon_tallies = {"Musk":0, "Hybrid":0, "Watermelon":0, "Winter": 0}

# Read through orders by type file and add to melon count
def get_orders():
    for l in f:
        data = l.split("|")
        melon_type = data[1]
        melon_count = int(data[2])
        melon_tallies[melon_type] += melon_count

# Close file
# f.close()

# List of prices for each melon
melon_prices = { "Musk": 1.15, "Hybrid": 1.30, "Watermelon": 1.75, "Winter": 4.00 }

# Add price of each melon times the amount of melons purchased 
def get_revenue():
    total_revenue = 0
    for melon_type in melon_tallies:
        price = melon_prices[melon_type]
        revenue = price * melon_tallies[melon_type]
        total_revenue += revenue
        # print("We sold %d %s melons at %0.2f each for a total of %0.2f" % (melon_tallies[melon_type], melon_type, price, revenue))
        print(f"We sold {melon_tallies[melon_type]} {melon_type} melons at {price:.2f} each for a total of {revenue:.2f}")

# Print separating divider
def print_revenue():
    print("******************************************")

# Open sales txt file and tally sales generated by the internet and salespeople

sales = [0, 0]

def sales_by_seller():
    f = open("orders-with-sales.txt")
    for line in f:
        d = line.split("|")
        if d[1] == "0":
            sales[0] += float(d[3])
        else:
            sales[1] += float(d[3])

# Print tallies
def print_tallies():
    print(f"Salespeople generated ${sales[1]:.2f} in revenue.")
    print(f"Internet sales generated ${sales[0]:.2f} in revenue.")



# Print out a saying depending on which seller had the greater amount of sales
def print_saying():
    if sales[1] > sales[0]:
        print("Guess there's some value to those salespeople after all.")
    else:
        print("Time to fire the sales team! Online sales rule all!")
    print("******************************************")

get_orders()
f.close()
get_revenue()
print_revenue()
sales_by_seller()
print_tallies()
print_saying()